# Base Image
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project
COPY . .

# Build NestJS apps
RUN npm run build

# Expose gateway port
EXPOSE 8000

# Start command
CMD ["node", "dist/apps/gateway/main.js"]