name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Gateway Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: true
          tags: parth731/codingsprints-gateway:${{ secrets.IMAGE_TAG }}

      - name: Build & Push Authentication Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: true
          tags: parth731/codingsprints-authentication:${{ secrets.IMAGE_TAG }}

      - name: Build & Push Tutorials Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: true
          tags: parth731/codingsprints-tutorials:${{ secrets.IMAGE_TAG }}
